[pytest]
markers =
    change: Tests that modify name of user
    check: Tests that check users name
    http: Tests that check HTTP Protocol
    api: Tests that use the GitHub API client
    database: Tests that use the Database client
    ui: Tests that use the UI client
